### ISSUE TITLE
bot spawning even if you are very close to them

### ISSUE THREAD

**Issue by BALIST0N** [sp-tarkov/server#957]
### SPT Version

3.10

### Project Type

Modules

### Expected Result

bot should not spawn when you are close the the bot spawn point

### Actual Result

i don't know exactly all the spawn points but here is what i have encountered : 

in dorms, scavs keep spawning indefinitely (first floor, end of the bulding near the closed door)  until the wave is finished 
in the partizan bulding area on shoreline (north east), scav and pmc ai keep spawning indefinitely , having more than 30 ai who keep spawning in 15 minutes

super wierd thing is , the respawned ai doesn't move and react to anything until after some time ?

### Steps To Reproduce

start a raid, rush to a big spawn zone in some maps, kills quickly ai, and wait for them to respawn too fast and too close to you

### Server Log

[server-2024-11-29.log](https://github.com/user-attachments/files/17961774/server-2024-11-29.log)

### BepinEx Log

[server-2024-11-29.log](https://github.com/user-attachments/files/17961775/server-2024-11-29.log)

### Client Log

[server-2024-11-29.log](https://github.com/user-attachments/files/17961776/server-2024-11-29.log)

**Comment by DrakiaXYZ** [comment]
This is a live (PvE) issue, we utilize BSG's spawn system, and don't actually have any control in our code over where the bots spawn as far as I'm aware

**Comment by BALIST0N** [comment]
i understand the possible non-resolving nature of the issue, maybe its some threshold value somewhere who is too low, or a check who doesn't check correctly, but the thing is, the client keeps calling the server for "bots/generate" , i know its for the server to regen new bots, but maybe it should call it less ...?

**Comment by BALIST0N** [comment]
okay after trying different things, it looks like the bot keeps spawning infinitely, looks like the game is counting the number of bots alive, and when one is killed, the game respawn one, and all ai keeps rushing you when they hear gunshots 
go to interchange close to mantis, there will be 50 scav infinitely spawning and rushing at you , combined with % of PMC spawning in the middle of the raid ai, this is becomming nonsense 
on reserve its the same thing, one ai killed is one ai respawning instantly, i was at gluhar garage spawn, and about 15 scavs keeps going where i was 
and when i killed a bot the game call instantly "bots/generate"

**Comment by DrakiaXYZ** [comment]
Yes, this is BSG's new spawn system, it's not something SPT implemented. Mods can be used to change it, but we try not to touch BSGs implementations of things just because we think they're wrong
