### ISSUE TITLE
traderPriceMultipler in "trader.json" doesnt affect on trader fleamarket prices

### ISSUE THREAD

**Issue by SwimUp** [sp-tarkov/server#968]
### SPT Version

3.9

### Project Type

Server

### Expected Result

Setting traderPriceMultipler also change trader fleamarket price

### Actual Result

Trader items on fleamarket is not used traderPriceMultipler 

### Steps To Reproduce

Change "traderPriceMultipler " in "trader.json", open trader UI and same item on fleamarket
For example:
![изображение](https://github.com/user-attachments/assets/37d2fb5d-e6f9-4d74-bff0-ccd198c6e264)

![изображение](https://github.com/user-attachments/assets/84c2bef9-c3ce-49b4-8c2b-c3316cabe67e)

### Server Log

[server-2024-12-03.log](https://github.com/user-attachments/files/17989509/server-2024-12-03.log)

### BepinEx Log

[LogOutput.log](https://github.com/user-attachments/files/17989511/LogOutput.log)

### Client Log

[2024.12.03_8-02-19_0.14.9.1.30626 traces.log](https://github.com/user-attachments/files/17989518/2024.12.03_8-02-19_0.14.9.1.30626.traces.log)

**Comment by chompDev** [comment]
I've made a change that should resolve the problem.

It will be part of 3.10.2
